### ISSUE TITLE
Add listen address argument

### ISSUE THREAD

**Issue by fussybeaver** [mit-pdos/noria-mysql#12]
I was playing around with noria on a cluster environment, and noticed that the mysql adapter only listens on a localhost address. Could we allow the mysql-adapter to have an additional argument `--address`, which points to the listen address, similar to how `noria-server` does it ? e.g. https://github.com/fussybeaver/noria-mysql/commit/e7c2238d198f900c12bd32d371a8ea67137082f3

I also had to peg the noria dependency at an older revision to get it to compile, because I think the `Row` interface was changed recently? I wasn't sure what was needed to fix that..

**Comment by jonhoo** [comment]
Yeah, that would make sense to add! Maybe we should just replace `--port` with `--address`?

I'm about to push a fix so that it works with the latest `master` :)
