### ISSUE TITLE
connection credentials (user, pass)

### ISSUE THREAD

**Issue by chmoder** [mit-pdos/noria-mysql#16]
Hi, my background with installing mysql includes either setting a root user password in a configuration file or as part of the install process.  What is the desired method for noria-mysql?  I have noria, noria-mysql, and noria-ui all running  (nice job on the docs by the way).  When I try to connect I see:
```
Jun 03 03:34:32.662 INFO listening on address 0.0.0.0:3306
  39.155999624s ERROR noria_mysql::backend: query can't be parsed
```

**Comment by jonhoo** [comment]
Hi there! There is currently no support for authentication with noria-mysql. Any username/password combination will work.

The particular error you are seeing suggests that the query you are issuing couldn't be parsed by https://github.com/ms705/nom-sql. Does it not give you a more detailed error message?

**Comment by chmoder** [comment]
I will look deeper into this, but when running `diesel migration run` There is a message like this:
```
thread 'conn-4' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "no view or table named \'__diesel_schema_migrations\'" }', src/backend.rs:1020:21
```

Indicating that i need to create a table called `__diesel_schema_migrations`.  Can you give me an example of how you would do that?  

another example
```
database setup --database-url mysql://root:pass@127.0.0.1/myapp
failed to parse query
```

**Comment by jonhoo** [comment]
Ah, I highly doubt that a db migration tool will work against Noria. They usually rely on a bunch of database-isms, such as being able to issue special commands to check whether a particular table already exists. If you wanted to do this normally, you'd just issue a `CREATE TABLE` against `noria-mysql`. You should be able to just connect manually with something like the `mysql` command-line tool :)

**Comment by chmoder** [comment]
You are correct!

`mysql -u root -p -h 127.0.0.1` with any password indeed lets me connect and CREAT TABLE worked as well.
